import { promises as fs } from "fs";
import path from "path";
import ExcelJS from "exceljs";
import { fileURLToPath } from "url";
import { weeklyCosting } from "../data.js";
import { pool } from "../db/pool.js";
import { config } from "../config.js";
import { sendMail } from "./mailerService.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const reportsDir = path.resolve(__dirname, "../../reports");

export async function generateWeeklyGmWorkbook() {
  await fs.mkdir(reportsDir, { recursive: true });

  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("GM Summary");

  sheet.columns = [
    { header: "Metric", key: "metric", width: 32 },
    { header: "Value", key: "value", width: 18 }
  ];

  sheet.addRows([
    { metric: "Week", value: weeklyCosting.week },
    { metric: "Fuel Cost", value: weeklyCosting.totalFuelCost },
    { metric: "Maintenance Cost", value: weeklyCosting.maintenanceCost },
    { metric: "Drilling & Blasting", value: weeklyCosting.drillingBlastingCost },
    { metric: "Logistics Cost", value: weeklyCosting.logisticsCost },
    { metric: "Cost Per Tonne", value: weeklyCosting.costPerTonne }
  ]);

  const fileName = `GM-Weekly-${weeklyCosting.week}-${Date.now()}.xlsx`;
  const filePath = path.join(reportsDir, fileName);
  await workbook.xlsx.writeFile(filePath);

  return {
    fileName,
    filePath
  };
}

export async function runWeeklyReportJob(triggeredBy: "manual" | "scheduler") {
  const start = await pool.query(
    `
      INSERT INTO automation_job_runs(job_name, status, details)
      VALUES('weekly_gm_report', 'running', $1::jsonb)
      RETURNING id
    `,
    [JSON.stringify({ triggeredBy })]
  );

  const jobId = start.rows[0]?.id as number;

  try {
    const report = await generateWeeklyGmWorkbook();
    let emailResult: { sent: boolean; reason?: string } = { sent: false, reason: "no_recipient" };

    if (config.weeklyReportRecipient) {
      emailResult = await sendMail({
        to: config.weeklyReportRecipient,
        subject: `IRONLOG Weekly GM Report ${weeklyCosting.week}`,
        text: "Attached is the latest weekly GM report generated by IRONLOG automation.",
        attachments: [{ filename: report.fileName, path: report.filePath }]
      });
    }

    await pool.query(
      `
        UPDATE automation_job_runs
        SET status = 'success', details = $2::jsonb, finished_at = NOW()
        WHERE id = $1
      `,
      [jobId, JSON.stringify({ triggeredBy, report, emailResult })]
    );

    await pool.query(
      `
        INSERT INTO rbac_audit_logs(action, target_type, target_id, metadata)
        VALUES('automation.weekly_gm.run', 'automation_job', $1, $2::jsonb)
      `,
      [String(jobId), JSON.stringify({ triggeredBy, report, emailResult })]
    );

    return { jobId, report, emailResult };
  } catch (error) {
    await pool.query(
      `
        UPDATE automation_job_runs
        SET status = 'failed', details = $2::jsonb, finished_at = NOW()
        WHERE id = $1
      `,
      [jobId, JSON.stringify({ triggeredBy, error: error instanceof Error ? error.message : "unknown" })]
    );
    throw error;
  }
}
